### ISSUE TITLE
Can you make a operation guide?

### ISSUE THREAD

**Issue by anqier0468** [omenyayl/dataset-annotator#8]
Can you make a operation guide? 
I don't know how to finish annotation with the polyline style.

**Comment by omenyayl** [comment]
Yeah sorry, it's right-click :D

We'll add a documentation in README for now

**Comment by omenyayl** [comment]
Should we add a button to navigate to the help page in the hamburger menu or add a new floating action button with a question mark icon?

EDIT: I'll just add a help icon to the right of the navbar

**Comment by omenyayl** [comment]
added a help page that is accessible by clicking the question mark at the top right of the window
